version: '3'

services:
  payload:
    build:
      context: ..
      dockerfile: Dockerfile
    #   args:
    #     NEXT_PUBLIC_SERVER_URL: http://localhost:3000
    #   secrets:
    #     - database_url
    #     - payload_secret
    # #ports:
    #  - '3000:3000'
    networks:
      - nginx
      - shared_postgres
    # env_file:
    #   - variables.env

# secrets:
#   database_url:
#     file: ./secrets/database_url
#   payload_secret:
#     file: ./secrets/payload_secret
#
networks:
  nginx:
    external: true
  shared_postgres:
    external: true
